"""Comprehensive Master Directory of NSE Listed Equity Symbols, Company Names, and Industries.
Enables sub-millisecond local autocomplete across the entire NSE equity universe
with automatic live NSE API fallback for newly listed equities.
"""

from typing import Dict, List, Optional

# Comprehensive master list of active NSE Equities
NSE_ALL_EQUITIES_MASTER: List[Dict[str, str]] = [
    # --- Top Nifty 50 & Heavyweights ---
    {"symbol": "RELIANCE", "company_name": "Reliance Industries Limited", "industry": "Oil & Gas"},
    {"symbol": "TCS", "company_name": "Tata Consultancy Services Limited", "industry": "IT Services"},
    {"symbol": "HDFCBANK", "company_name": "HDFC Bank Limited", "industry": "Private Banking"},
    {"symbol": "INFY", "company_name": "Infosys Limited", "industry": "IT Services"},
    {"symbol": "ICICIBANK", "company_name": "ICICI Bank Limited", "industry": "Private Banking"},
    {"symbol": "BHARTIARTL", "company_name": "Bharti Airtel Limited", "industry": "Telecommunication"},
    {"symbol": "SBIN", "company_name": "State Bank of India", "industry": "Public Banking"},
    {"symbol": "LICI", "company_name": "Life Insurance Corporation of India", "industry": "Insurance"},
    {"symbol": "ITC", "company_name": "ITC Limited", "industry": "FMCG / Tobacco"},
    {"symbol": "HINDUNILVR", "company_name": "Hindustan Unilever Limited", "industry": "FMCG"},
    {"symbol": "LT", "company_name": "Larsen & Toubro Limited", "industry": "Construction & Engineering"},
    {"symbol": "BAJFINANCE", "company_name": "Bajaj Finance Limited", "industry": "Financial Services / NBFC"},
    {"symbol": "HCLTECH", "company_name": "HCL Technologies Limited", "industry": "IT Services"},
    {"symbol": "MARUTI", "company_name": "Maruti Suzuki India Limited", "industry": "Automobiles"},
    {"symbol": "SUNPHARMA", "company_name": "Sun Pharmaceutical Industries Limited", "industry": "Pharmaceuticals"},
    {"symbol": "ADANIENT", "company_name": "Adani Enterprises Limited", "industry": "Trading & Logistics"},
    {"symbol": "KOTAKBANK", "company_name": "Kotak Mahindra Bank Limited", "industry": "Private Banking"},
    {"symbol": "TITAN", "company_name": "Titan Company Limited", "industry": "Consumer Durables / Jewellery"},
    {"symbol": "ONGC", "company_name": "Oil & Natural Gas Corporation Limited", "industry": "Oil & Gas Exploration"},
    {"symbol": "TATAMOTORS", "company_name": "Tata Motors Limited", "industry": "Automobiles"},
    {"symbol": "NTPC", "company_name": "NTPC Limited", "industry": "Power Generation"},
    {"symbol": "AXISBANK", "company_name": "Axis Bank Limited", "industry": "Private Banking"},
    {"symbol": "ADANIPORTS", "company_name": "Adani Ports and Special Economic Zone Limited", "industry": "Infrastructure / Ports"},
    {"symbol": "POWERGRID", "company_name": "Power Grid Corporation of India Limited", "industry": "Power Transmission"},
    {"symbol": "COALINDIA", "company_name": "Coal India Limited", "industry": "Mining & Minerals"},
    {"symbol": "ULTRACEMCO", "company_name": "UltraTech Cement Limited", "industry": "Cement & Building Materials"},
    {"symbol": "BAJAJFINSV", "company_name": "Bajaj Finserv Limited", "industry": "Financial Services"},
    {"symbol": "WIPRO", "company_name": "Wipro Limited", "industry": "IT Services"},
    {"symbol": "M&M", "company_name": "Mahindra & Mahindra Limited", "industry": "Automobiles & Farm Equipment"},
    {"symbol": "ASIANPAINT", "company_name": "Asian Paints Limited", "industry": "Paints & Coatings"},
    {"symbol": "JSWSTEEL", "company_name": "JSW Steel Limited", "industry": "Metals & Steel"},
    {"symbol": "TATASTEEL", "company_name": "Tata Steel Limited", "industry": "Metals & Steel"},
    {"symbol": "SIEMENS", "company_name": "Siemens Limited", "industry": "Capital Goods & Engineering"},
    {"symbol": "IOC", "company_name": "Indian Oil Corporation Limited", "industry": "Oil Refineries"},
    {"symbol": "ZOMATO", "company_name": "Zomato Limited", "industry": "E-Commerce / Food Delivery"},
    {"symbol": "JIOFIN", "company_name": "Jio Financial Services Limited", "industry": "Financial Services"},
    {"symbol": "NESTLEIND", "company_name": "Nestle India Limited", "industry": "FMCG / Food Products"},
    {"symbol": "GRASIM", "company_name": "Grasim Industries Limited", "industry": "Chemicals & Textiles"},
    {"symbol": "SBILIFE", "company_name": "SBI Life Insurance Company Limited", "industry": "Life Insurance"},
    {"symbol": "TECHM", "company_name": "Tech Mahindra Limited", "industry": "IT Services"},
    {"symbol": "HDFCLIFE", "company_name": "HDFC Life Insurance Company Limited", "industry": "Life Insurance"},
    {"symbol": "BRITANNIA", "company_name": "Britannia Industries Limited", "industry": "FMCG / Bakery"},
    {"symbol": "HINDALCO", "company_name": "Hindalco Industries Limited", "industry": "Aluminium & Metals"},
    {"symbol": "BEL", "company_name": "Bharat Electronics Limited", "industry": "Defence & Electronics"},
    {"symbol": "HAL", "company_name": "Hindustan Aeronautics Limited", "industry": "Aerospace & Defence"},
    {"symbol": "INDUSINDBK", "company_name": "IndusInd Bank Limited", "industry": "Private Banking"},
    {"symbol": "EICHERMOT", "company_name": "Eicher Motors Limited", "industry": "Automobiles / Two-Wheelers"},
    {"symbol": "CIPLA", "company_name": "Cipla Limited", "industry": "Pharmaceuticals"},
    {"symbol": "APOLLOHOSP", "company_name": "Apollo Hospitals Enterprise Limited", "industry": "Healthcare & Hospitals"},
    {"symbol": "TATACONSUM", "company_name": "Tata Consumer Products Limited", "industry": "FMCG / Beverages"},
    {"symbol": "DRREDDY", "company_name": "Dr. Reddy's Laboratories Limited", "industry": "Pharmaceuticals"},
    {"symbol": "BPCL", "company_name": "Bharat Petroleum Corporation Limited", "industry": "Oil Refineries"},
    {"symbol": "SHRIRAMFIN", "company_name": "Shriram Finance Limited", "industry": "NBFC"},
    {"symbol": "HEROMOTOCO", "company_name": "Hero MotoCorp Limited", "industry": "Automobiles / Two-Wheelers"},
    {"symbol": "TRENT", "company_name": "Trent Limited", "industry": "Retail & Apparel"},
    {"symbol": "DIVISLAB", "company_name": "Divi's Laboratories Limited", "industry": "Pharmaceuticals / APIs"},

    # --- Nifty Next 50 & High-Growth Midcaps ---
    {"symbol": "ADANIENSOL", "company_name": "Adani Energy Solutions Limited", "industry": "Power Transmission"},
    {"symbol": "ADANIGREEN", "company_name": "Adani Green Energy Limited", "industry": "Renewable Energy"},
    {"symbol": "ADANIPOWER", "company_name": "Adani Power Limited", "industry": "Thermal Power"},
    {"symbol": "AMBUJACEM", "company_name": "Ambuja Cements Limited", "industry": "Cement"},
    {"symbol": "BANKBARODA", "company_name": "Bank of Baroda", "industry": "Public Banking"},
    {"symbol": "BOSCHLTD", "company_name": "Bosch Limited", "industry": "Auto Components"},
    {"symbol": "CANBK", "company_name": "Canara Bank", "industry": "Public Banking"},
    {"symbol": "CHOLAFIN", "company_name": "Cholamandalam Investment and Finance Co.", "industry": "NBFC"},
    {"symbol": "COLPAL", "company_name": "Colgate-Palmolive (India) Limited", "industry": "Personal Care"},
    {"symbol": "DABUR", "company_name": "Dabur India Limited", "industry": "Ayurveda / FMCG"},
    {"symbol": "DLF", "company_name": "DLF Limited", "industry": "Real Estate Development"},
    {"symbol": "GAIL", "company_name": "GAIL (India) Limited", "industry": "Natural Gas Transmission"},
    {"symbol": "GODREJCP", "company_name": "Godrej Consumer Products Limited", "industry": "FMCG"},
    {"symbol": "HAVELLS", "company_name": "Havells India Limited", "industry": "Consumer Electricals"},
    {"symbol": "ICICIGI", "company_name": "ICICI Lombard General Insurance Co.", "industry": "General Insurance"},
    {"symbol": "ICICIPRULI", "company_name": "ICICI Prudential Life Insurance Co.", "industry": "Life Insurance"},
    {"symbol": "INDIGO", "company_name": "InterGlobe Aviation Limited", "industry": "Airlines / Aviation"},
    {"symbol": "IRFC", "company_name": "Indian Railway Finance Corporation", "industry": "Railway Infrastructure / Finance"},
    {"symbol": "IREDA", "company_name": "Indian Renewable Energy Development Agency", "industry": "Renewable Energy Finance"},
    {"symbol": "JINDALSTEL", "company_name": "Jindal Steel & Power Limited", "industry": "Metals & Mining"},
    {"symbol": "LODHA", "company_name": "Macrotech Developers Limited", "industry": "Real Estate"},
    {"symbol": "LTIM", "company_name": "LTIMindtree Limited", "industry": "IT Services"},
    {"symbol": "MARICO", "company_name": "Marico Limited", "industry": "FMCG / Oils"},
    {"symbol": "MOTHERSON", "company_name": "Samvardhana Motherson International Ltd", "industry": "Auto Ancillaries"},
    {"symbol": "NAUKRI", "company_name": "Info Edge (India) Limited", "industry": "Internet & Classifieds"},
    {"symbol": "NHPC", "company_name": "NHPC Limited", "industry": "Hydroelectric Power"},
    {"symbol": "PFC", "company_name": "Power Finance Corporation Limited", "industry": "Power Sector Finance"},
    {"symbol": "PIDILITIND", "company_name": "Pidilite Industries Limited", "industry": "Speciality Chemicals & Adhesives"},
    {"symbol": "PNB", "company_name": "Punjab National Bank", "industry": "Public Banking"},
    {"symbol": "POLICYBZR", "company_name": "PB Fintech Limited", "industry": "Fintech / Insurance Aggregator"},
    {"symbol": "POLYCAB", "company_name": "Polycab India Limited", "industry": "Cables & Wires"},
    {"symbol": "RECLTD", "company_name": "REC Limited", "industry": "Power Infrastructure Finance"},
    {"symbol": "RVNL", "company_name": "Rail Vikas Nigam Limited", "industry": "Railway Infrastructure"},
    {"symbol": "SRF", "company_name": "SRF Limited", "industry": "Speciality Chemicals & Packaging"},
    {"symbol": "TATAPOWER", "company_name": "Tata Power Company Limited", "industry": "Integrated Power & EV Infra"},
    {"symbol": "TORNTPHARM", "company_name": "Torrent Pharmaceuticals Limited", "industry": "Pharmaceuticals"},
    {"symbol": "TVSMOTOR", "company_name": "TVS Motor Company Limited", "industry": "Automobiles / Two-Wheelers"},
    {"symbol": "UNIONBANK", "company_name": "Union Bank of India", "industry": "Public Banking"},
    {"symbol": "UNITDSPR", "company_name": "United Spirits Limited", "industry": "Beverages / Alco-bev"},
    {"symbol": "VBL", "company_name": "Varun Beverages Limited", "industry": "Beverages / Bottling"},
    {"symbol": "VEDL", "company_name": "Vedanta Limited", "industry": "Diversified Metals & Mining"},
    {"symbol": "ZYDUSLIFE", "company_name": "Zydus Lifesciences Limited", "industry": "Pharmaceuticals"},

    # --- Popular Market Equities, Railways, Defence & PSU ---
    {"symbol": "ABCAPITAL", "company_name": "Aditya Birla Capital Limited", "industry": "Financial Services"},
    {"symbol": "ABFRL", "company_name": "Aditya Birla Fashion and Retail Limited", "industry": "Retail & Fashion"},
    {"symbol": "ACC", "company_name": "ACC Limited", "industry": "Cement"},
    {"symbol": "ANGELONE", "company_name": "Angel One Limited", "industry": "Stockbroking & Fintech"},
    {"symbol": "APOLLOTYRE", "company_name": "Apollo Tyres Limited", "industry": "Tyres & Rubber"},
    {"symbol": "ASHOKLEY", "company_name": "Ashok Leyland Limited", "industry": "Commercial Vehicles"},
    {"symbol": "ASTRAL", "company_name": "Astral Limited", "industry": "Pipes & Fittings"},
    {"symbol": "ATGL", "company_name": "Adani Total Gas Limited", "industry": "City Gas Distribution"},
    {"symbol": "AUROPHARMA", "company_name": "Aurobindo Pharma Limited", "industry": "Pharmaceuticals"},
    {"symbol": "BALKRISIND", "company_name": "Balkrishna Industries Limited", "industry": "Tyres / Off-Highway"},
    {"symbol": "BANDHANBNK", "company_name": "Bandhan Bank Limited", "industry": "Banking"},
    {"symbol": "BATAINDIA", "company_name": "Bata India Limited", "industry": "Footwear"},
    {"symbol": "BERGEPAINT", "company_name": "Berger Paints India Limited", "industry": "Paints"},
    {"symbol": "BHARATFORG", "company_name": "Bharat Forge Limited", "industry": "Forging & Defence"},
    {"symbol": "BHEL", "company_name": "Bharat Heavy Electricals Limited", "industry": "Heavy Electrical Equipment"},
    {"symbol": "BIOCON", "company_name": "Biocon Limited", "industry": "Biotechnology / Biosimilars"},
    {"symbol": "CDSL", "company_name": "Central Depository Services (India) Limited", "industry": "Capital Market Infrastructure"},
    {"symbol": "COCHINSHIP", "company_name": "Cochin Shipyard Limited", "industry": "Shipbuilding & Defence"},
    {"symbol": "CONCOR", "company_name": "Container Corporation of India Limited", "industry": "Logistics & Freight"},
    {"symbol": "CROMPTON", "company_name": "Crompton Greaves Consumer Electricals", "industry": "Consumer Electricals"},
    {"symbol": "CUMMINSIND", "company_name": "Cummins India Limited", "industry": "Engines & Heavy Machinery"},
    {"symbol": "DEEPAKNTR", "company_name": "Deepak Nitrite Limited", "industry": "Speciality Chemicals"},
    {"symbol": "DELHIVERY", "company_name": "Delhivery Limited", "industry": "Logistics & Supply Chain"},
    {"symbol": "DIXON", "company_name": "Dixon Technologies (India) Limited", "industry": "Electronics Manufacturing"},
    {"symbol": "ESCORTS", "company_name": "Escorts Kubota Limited", "industry": "Tractors & Agri Machinery"},
    {"symbol": "EXIDEIND", "company_name": "Exide Industries Limited", "industry": "Auto Batteries & Energy Storage"},
    {"symbol": "FEDERALBNK", "company_name": "The Federal Bank Limited", "industry": "Private Banking"},
    {"symbol": "GLENMARK", "company_name": "Glenmark Pharmaceuticals Limited", "industry": "Pharmaceuticals"},
    {"symbol": "GMRAIRPORT", "company_name": "GMR Airports Infrastructure Limited", "industry": "Airport Infrastructure"},
    {"symbol": "GNFC", "company_name": "Gujarat Narmada Valley Fertilizers & Chem", "industry": "Fertilizers & Chemicals"},
    {"symbol": "GODREJPROP", "company_name": "Godrej Properties Limited", "industry": "Real Estate"},
    {"symbol": "GRANULES", "company_name": "Granules India Limited", "industry": "Pharmaceuticals"},
    {"symbol": "GUJGASLTD", "company_name": "Gujarat Gas Limited", "industry": "City Gas Distribution"},
    {"symbol": "HDFCAMC", "company_name": "HDFC Asset Management Company Limited", "industry": "Asset Management / Mutual Funds"},
    {"symbol": "HINDCOPPER", "company_name": "Hindustan Copper Limited", "industry": "Copper Mining"},
    {"symbol": "HINDPETRO", "company_name": "Hindustan Petroleum Corporation Limited", "industry": "Oil Refineries"},
    {"symbol": "HINDZINC", "company_name": "Hindustan Zinc Limited", "industry": "Zinc & Silver Mining"},
    {"symbol": "HUDCO", "company_name": "Housing & Urban Development Corporation", "industry": "Housing Finance & Infrastructure"},
    {"symbol": "IDEA", "company_name": "Vodafone Idea Limited", "industry": "Telecommunication"},
    {"symbol": "IDFCFIRSTB", "company_name": "IDFC First Bank Limited", "industry": "Private Banking"},
    {"symbol": "IEX", "company_name": "Indian Energy Exchange Limited", "industry": "Energy Trading Exchange"},
    {"symbol": "IGL", "company_name": "Indraprastha Gas Limited", "industry": "City Gas Distribution"},
    {"symbol": "INDIACEM", "company_name": "The India Cements Limited", "industry": "Cement"},
    {"symbol": "INDIAMART", "company_name": "IndiaMART InterMESH Limited", "industry": "B2B E-Commerce"},
    {"symbol": "INDHOTEL", "company_name": "The Indian Hotels Company Limited", "industry": "Hotels & Hospitality (Taj)"},
    {"symbol": "INDUSTOWER", "company_name": "Indus Towers Limited", "industry": "Telecom Infrastructure"},
    {"symbol": "IOB", "company_name": "Indian Overseas Bank", "industry": "Public Banking"},
    {"symbol": "IPCALAB", "company_name": "IPCA Laboratories Limited", "industry": "Pharmaceuticals"},
    {"symbol": "IRCTC", "company_name": "Indian Railway Catering & Tourism Corp.", "industry": "Railway Catering & Travel"},
    {"symbol": "IRB", "company_name": "IRB Infrastructure Developers Limited", "industry": "Roads & Highways"},
    {"symbol": "J&KBANK", "company_name": "The Jammu & Kashmir Bank Limited", "industry": "Banking"},
    {"symbol": "JASCH", "company_name": "Jasch Industries Limited", "industry": "Plastics & Synthetic Leather"},
    {"symbol": "JBCHEPHARM", "company_name": "JB Chemicals & Pharmaceuticals Limited", "industry": "Pharmaceuticals"},
    {"symbol": "JKCEMENT", "company_name": "JK Cement Limited", "industry": "Cement"},
    {"symbol": "JSWENERGY", "company_name": "JSW Energy Limited", "industry": "Thermal & Renewable Power"},
    {"symbol": "JSWINFRA", "company_name": "JSW Infrastructure Limited", "industry": "Ports & Logistics"},
    {"symbol": "JUBLFOOD", "company_name": "Jubilant FoodWorks Limited", "industry": "QSR (Domino's Pizza)"},
    {"symbol": "KALYANKJIL", "company_name": "Kalyan Jewellers India Limited", "industry": "Jewellery & Retail"},
    {"symbol": "KPITTECH", "company_name": "KPIT Technologies Limited", "industry": "Automotive Software & EV Tech"},
    {"symbol": "L&TFH", "company_name": "L&T Finance Holdings Limited", "industry": "NBFC / Retail Finance"},
    {"symbol": "LAURUSLABS", "company_name": "Laurus Labs Limited", "industry": "Pharmaceuticals / APIs"},
    {"symbol": "LICHSGFIN", "company_name": "LIC Housing Finance Limited", "industry": "Housing Finance"},
    {"symbol": "LUPIN", "company_name": "Lupin Limited", "industry": "Pharmaceuticals"},
    {"symbol": "MANAPPURAM", "company_name": "Manappuram Finance Limited", "industry": "Gold Loan / NBFC"},
    {"symbol": "MAXHEALTH", "company_name": "Max Healthcare Institute Limited", "industry": "Healthcare & Hospitals"},
    {"symbol": "MAZDOCK", "company_name": "Mazagon Dock Shipbuilders Limited", "industry": "Defence & Warships"},
    {"symbol": "MCX", "company_name": "Multi Commodity Exchange of India Limited", "industry": "Commodity Exchange"},
    {"symbol": "METROPOLIS", "company_name": "Metropolis Healthcare Limited", "industry": "Diagnostics & Pathology"},
    {"symbol": "MFSL", "company_name": "Max Financial Services Limited", "industry": "Life Insurance"},
    {"symbol": "MGL", "company_name": "Mahanagar Gas Limited", "industry": "City Gas Distribution"},
    {"symbol": "MPHASIS", "company_name": "Mphasis Limited", "industry": "IT Services"},
    {"symbol": "MRF", "company_name": "MRF Limited", "industry": "Tyres & Rubber"},
    {"symbol": "MUTHOOTFIN", "company_name": "Muthoot Finance Limited", "industry": "Gold Loans"},
    {"symbol": "NATIONALUM", "company_name": "National Aluminium Company Limited (NALCO)", "industry": "Aluminium Mining"},
    {"symbol": "NBCC", "company_name": "NBCC (India) Limited", "industry": "Construction & Real Estate PMC"},
    {"symbol": "NCC", "company_name": "NCC Limited", "industry": "Infrastructure Construction"},
    {"symbol": "NMDC", "company_name": "NMDC Limited", "industry": "Iron Ore Mining"},
    {"symbol": "NOCIL", "company_name": "NOCIL Limited", "industry": "Rubber Chemicals"},
    {"symbol": "NTPCGREEN", "company_name": "NTPC Green Energy Limited", "industry": "Renewable Power"},
    {"symbol": "NYKAA", "company_name": "FSN E-Commerce Ventures Limited", "industry": "Beauty & Fashion E-Commerce"},
    {"symbol": "OBEROIRLTY", "company_name": "Oberoi Realty Limited", "industry": "Real Estate"},
    {"symbol": "OFSS", "company_name": "Oracle Financial Services Software Limited", "industry": "Banking Software"},
    {"symbol": "OIL", "company_name": "Oil India Limited", "industry": "Oil Exploration"},
    {"symbol": "PAGEIND", "company_name": "Page Industries Limited (Jockey)", "industry": "Apparel & Innerwear"},
    {"symbol": "PATANJALI", "company_name": "Patanjali Foods Limited", "industry": "Edible Oils & FMCG"},
    {"symbol": "PAYTM", "company_name": "One97 Communications Limited (Paytm)", "industry": "Fintech & Payments"},
    {"symbol": "PERSISTENT", "company_name": "Persistent Systems Limited", "industry": "IT & Digital Engineering"},
    {"symbol": "PETRONET", "company_name": "Petronet LNG Limited", "industry": "LNG Terminals"},
    {"symbol": "PFIZER", "company_name": "Pfizer Limited", "industry": "Pharmaceuticals"},
    {"symbol": "PHOENIXLTD", "company_name": "The Phoenix Mills Limited", "industry": "Retail Malls & Commercial"},
    {"symbol": "POONAWALLA", "company_name": "Poonawalla Fincorp Limited", "industry": "NBFC"},
    {"symbol": "PRESTIGE", "company_name": "Prestige Estates Projects Limited", "industry": "Real Estate"},
    {"symbol": "PVRINOX", "company_name": "PVR INOX Limited", "industry": "Movie Exhibition & Multiplexes"},
    {"symbol": "RADICO", "company_name": "Radico Khaitan Limited", "industry": "Distilleries & Spirits"},
    {"symbol": "RAMCOCEM", "company_name": "The Ramco Cements Limited", "industry": "Cement"},
    {"symbol": "RBLBANK", "company_name": "RBL Bank Limited", "industry": "Private Banking"},
    {"symbol": "RCF", "company_name": "Rashtriya Chemicals & Fertilizers Limited", "industry": "Fertilizers"},
    {"symbol": "REDINGTON", "company_name": "Redington Limited", "industry": "IT & Electronics Distribution"},
    {"symbol": "RPOWER", "company_name": "Reliance Power Limited", "industry": "Power Generation"},
    {"symbol": "RITES", "company_name": "RITES Limited", "industry": "Railway Consultancy & Engineering"},
    {"symbol": "SAIL", "company_name": "Steel Authority of India Limited", "industry": "Steel Manufacturing"},
    {"symbol": "SBICARD", "company_name": "SBI Cards and Payment Services Limited", "industry": "Credit Cards & Payments"},
    {"symbol": "SCHAEFFLER", "company_name": "Schaeffler India Limited", "industry": "Bearings & Industrial"},
    {"symbol": "SHREECEM", "company_name": "Shree Cement Limited", "industry": "Cement"},
    {"symbol": "SOLARINDS", "company_name": "Solar Industries India Limited", "industry": "Industrial Explosives & Defence"},
    {"symbol": "SONACOMS", "company_name": "Sona BLW Precision Forgings Limited", "industry": "EV & Driveline Components"},
    {"symbol": "STARHEALTH", "company_name": "Star Health and Allied Insurance Company", "industry": "Health Insurance"},
    {"symbol": "SUNTV", "company_name": "Sun TV Network Limited", "industry": "Broadcasting & Media"},
    {"symbol": "SUPREMEIND", "company_name": "The Supreme Industries Limited", "industry": "Plastics & Piping"},
    {"symbol": "SUZLON", "company_name": "Suzlon Energy Limited", "industry": "Wind Energy & Turbines"},
    {"symbol": "SYNGENE", "company_name": "Syngene International Limited", "industry": "Contract Research / Pharma"},
    {"symbol": "TATACHEM", "company_name": "Tata Chemicals Limited", "industry": "Chemicals & Soda Ash"},
    {"symbol": "TATACOMM", "company_name": "Tata Communications Limited", "industry": "Enterprise Telecom & Cloud"},
    {"symbol": "TATAELXSI", "company_name": "Tata Elxsi Limited", "industry": "Design & Technology Services"},
    {"symbol": "TATAINVEST", "company_name": "Tata Investment Corporation Limited", "industry": "Investment Holding"},
    {"symbol": "TATATECH", "company_name": "Tata Technologies Limited", "industry": "Engineering & R&D Services"},
    {"symbol": "TEJASNET", "company_name": "Tejas Networks Limited", "industry": "Telecom Equipment & 5G"},
    {"symbol": "THERMAX", "company_name": "Thermax Limited", "industry": "Energy & Environment Engineering"},
    {"symbol": "TORNTPOWER", "company_name": "Torrent Power Limited", "industry": "Power Generation & Distribution"},
    {"symbol": "TRIDENT", "company_name": "Trident Limited", "industry": "Textiles & Paper"},
    {"symbol": "UBL", "company_name": "United Breweries Limited (Kingfisher)", "industry": "Breweries & Beer"},
    {"symbol": "UCOBANK", "company_name": "UCO Bank", "industry": "Public Banking"},
    {"symbol": "UNOMINDA", "company_name": "Uno Minda Limited", "industry": "Auto Components"},
    {"symbol": "UPL", "company_name": "UPL Limited", "industry": "Agrochemicals & Crop Protection"},
    {"symbol": "VAIBHAVGBL", "company_name": "Vaibhav Global Limited", "industry": "E-Commerce / Jewellery"},
    {"symbol": "VGUARD", "company_name": "V-Guard Industries Limited", "industry": "Consumer Electricals"},
    {"symbol": "VOLTAS", "company_name": "Voltas Limited", "industry": "Air Conditioning & Cooling"},
    {"symbol": "WHIRLPOOL", "company_name": "Whirlpool of India Limited", "industry": "Home Appliances"},
    {"symbol": "YESBANK", "company_name": "Yes Bank Limited", "industry": "Private Banking"},
    {"symbol": "ZEEL", "company_name": "Zee Entertainment Enterprises Limited", "industry": "Media & Entertainment"},
    {"symbol": "ZENSARTECH", "company_name": "Zensar Technologies Limited", "industry": "IT Services"},
]

# Quick index for symbol lookups
_SYMBOL_MAP = {item["symbol"].upper(): item for item in NSE_ALL_EQUITIES_MASTER}

def lookup_master_symbol(symbol: str) -> Optional[Dict[str, str]]:
    """Returns metadata for a given symbol from the master cache."""
    return _SYMBOL_MAP.get(symbol.strip().upper())

def search_master_equities(query: str, limit: int = 30) -> List[Dict[str, str]]:
    """Fast prefix and fuzzy matching on symbol and company name across all equities."""
    q = query.strip().upper()
    if not q:
        return []

    exact_matches = []
    prefix_matches = []
    contains_matches = []

    for item in NSE_ALL_EQUITIES_MASTER:
        sym = item["symbol"]
        name = item["company_name"].upper()

        if sym == q:
            exact_matches.append(item)
        elif sym.startswith(q):
            prefix_matches.append(item)
        elif q in sym or q in name:
            contains_matches.append(item)

    combined = exact_matches + prefix_matches + contains_matches
    return combined[:limit]
